---

cartpolereduced:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 8000
  import_from: rl.cartpole
  import_benchmark: CartpoleReduced

cartpolefull:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 8000
  import_from: rl.cartpole
  import_benchmark: CartpoleFull

xgboost:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 4000
  import_from: ml.xgboost_benchmark
  import_benchmark: XGBoostBenchmark
  main_fidelity: subsample
  is_surrogate: false

learna:
  time_limit_in_s: 172800
  cutoff_in_s: 40000
  mem_limit_in_mb: 4000
  import_from: rl.learna_benchmark
  import_benchmark: Learna
  num_iterations: 3

metalearna:
  time_limit_in_s: 345600
  cutoff_in_s: 40000
  mem_limit_in_mb: 4000
  import_from: rl.learna_benchmark
  import_benchmark: MetaLearna
  num_iterations: 3

NASCifar10ABenchmark:
  time_limit_in_s: 500000
  cutoff_in_s: 500000
  mem_limit_in_mb: 16000
  import_from: nas.nasbench_101
  import_benchmark: NASCifar10ABenchmark
  is_surrogate: true

NASCifar10BBenchmark:
  time_limit_in_s: 500000
  cutoff_in_s: 500000
  mem_limit_in_mb: 16000
  import_from: nas.nasbench_101
  import_benchmark: NASCifar10BBenchmark
  is_surrogate: true

NASCifar10CBenchmark:
  time_limit_in_s: 500000
  cutoff_in_s: 500000
  mem_limit_in_mb: 16000
  import_from: nas.nasbench_101
  import_benchmark: NASCifar10CBenchmark
  is_surrogate: true

SliceLocalizationBenchmark:
  time_limit_in_s: 500000
  cutoff_in_s: 500000
  mem_limit_in_mb: 16000
  import_from: nas.tabular_benchmarks
  import_benchmark: SliceLocalizationBenchmark
  is_surrogate: true

ProteinStructureBenchmark:
  time_limit_in_s: 500000
  cutoff_in_s: 500000
  mem_limit_in_mb: 16000
  import_from: nas.tabular_benchmarks
  import_benchmark: ProteinStructureBenchmark
  is_surrogate: true

NavalPropulsionBenchmark:
  time_limit_in_s: 500000
  cutoff_in_s: 500000
  mem_limit_in_mb: 16000
  import_from: nas.tabular_benchmarks
  import_benchmark: NavalPropulsionBenchmark
  is_surrogate: true

ParkinsonsTelemonitoringBenchmark:
  time_limit_in_s: 500000
  cutoff_in_s: 500000
  mem_limit_in_mb: 16000
  import_from: nas.tabular_benchmarks
  import_benchmark: ParkinsonsTelemonitoringBenchmark
  is_surrogate: true

Cifar10NasBench201Benchmark:
  time_limit_in_s: 10000000
  cutoff_in_s: 10000000
  mem_limit_in_mb: 16000
  import_from: nas.nasbench_201
  import_benchmark: Cifar10NasBench201Benchmark
  is_surrogate: true

Cifar10ValidNasBench201Benchmark:
  time_limit_in_s: 10000000
  cutoff_in_s: 10000000
  mem_limit_in_mb: 16000
  import_from: nas.nasbench_201
  import_benchmark: Cifar10ValidNasBench201Benchmark
  is_surrogate: true

Cifar100NasBench201Benchmark:
  time_limit_in_s: 10000000
  cutoff_in_s: 10000000
  mem_limit_in_mb: 16000
  import_from: nas.nasbench_201
  import_benchmark: Cifar100NasBench201Benchmark
  is_surrogate: true

ImageNetNasBench201Benchmark:
  time_limit_in_s: 10000000
  cutoff_in_s: 10000000
  mem_limit_in_mb: 16000
  import_from: nas.nasbench_201
  import_benchmark: ImageNetNasBench201Benchmark
  is_surrogate: true

...
