---
cartpolereduced:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 8000
  import_from: rl.cartpole
  import_benchmark: CartpoleReduced

cartpolefull:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 8000
  import_from: rl.cartpole
  import_benchmark: CartpoleFull
  
xgboost:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 4000
  import_from: ml.xgboost_benchmark
  import_benchmark: XGBoostBenchmark
  main_fidelity: subsample
  is_surrogate: true
  
learna:
  time_limit_in_s: 172800
  cutoff_in_s: 40000
  mem_limit_in_mb: 4000
  import_from: rl.learna_benchmark
  import_benchmark: Learna

metalearna:
  time_limit_in_s: 345600
  cutoff_in_s: 40000
  mem_limit_in_mb: 4000
  import_from: rl.learna_benchmark
  import_benchmark: MetaLearna

NASCifar10ABenchmark:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 16000
  import_from: nas.nasbench_101
  import_benchmark: NASCifar10ABenchmark
  is_surrogate:  true

NASCifar10BBenchmark:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 16000
  import_from: nas.nasbench_101
  import_benchmark: NASCifar10BBenchmark
  is_surrogate:  true

NASCifar10CBenchmark:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 16000,
  import_from: nas.nasbench_101
  import_benchmark: NASCifar10CBenchmark
  is_surrogate:  true},

SliceLocalizationBenchmark:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 16000,
  import_from: nas.tabular_benchmarks
  import_benchmark: SliceLocalizationBenchmark
  is_surrogate:  true

ProteinStructureBenchmark:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 16000,
   import_from: nas.tabular_benchmarks
  import_benchmark: ProteinStructureBenchmark
  is_surrogate:  true

NavalPropulsionBenchmark:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 16000,
  import_from: nas.tabular_benchmarks
  import_benchmark: NavalPropulsionBenchmark
  is_surrogate:  true

ParkinsonsTelemonitoringBenchmark:
  time_limit_in_s: 4000
  cutoff_in_s: 1800
  mem_limit_in_mb: 16000,
   import_from: nas.tabular_benchmarks
  import_benchmark: ParkinsonsTelemonitoringBenchmark
  is_surrogate:  true

...