---
# PURE RANDOMSEARCH################################################################################################### #
randomsearch:
  optimizer: randomsearch
  display_name: "random search"

# DRAGONFLY DEFAULT ################################################################################################## #
dragonfly_default:
  optimizer: dragonfly
  init_iter_per_dim: 10
  init_capital_frac: 0.1 # Ignored since 'init_iter_per_dim' is present

# DRAGONFLY REALTIME ################################################################################################# #
dragonfly_realtime:
  optimizer: dragonfly
  init_capital_frac: 0.1

# SMAC ##################################################################################################### #
smac_hb_eta_3:
  optimizer: smac_hb
  eta: 3
  max_stages: 5
  display_name: "SMAC-HB"

smac_sh_eta_3:
  optimizer: smac_sh
  eta: 3
  max_stages: 5
  display_name: "SMAC-HB"

smac_hb_eta_2:
  optimizer: smac_hb
  eta: 2
  max_stages: 5
  display_name: "SMAC-SH (eta2)"

smac_sh_eta_2:
  optimizer: smac_sh
  eta: 2
  max_stages: 5
  display_name: "SMAC-SH (eta2)"

# HPBANDSTER BOHB #################################################################################################### #
hpbandster_bohb_eta_3:
  optimizer: hpbandster_bohb
  eta: 3
  max_stages: 5
  display_name: "BOHB"

hpbandster_bohb_eta_2:
  optimizer: hpbandster_bohb
  eta: 2
  max_stages: 5
  display_name: "BOHB (eta2)"

hpbandster_hb_eta_3:
  optimizer: hpbandster_hb
  eta: 3
  max_stages: 5
  display_name: "HB"

hpbandster_hb_eta_2:
  optimizer: hpbandster_hb
  eta: 2
  max_stages: 5
  display_name: "HB (eta2)"

hpbandster_sh_eta_3:
  optimizer: hpbandster_sh
  eta: 3
  max_stages: 5
  display_name: "SH"

hpbandster_sh_eta_2:
  optimizer: hpbandster_sh
  eta: 2
  max_stages: 5
  display_name: "SH (eta2)"

...
