---
# SMAC HYPERBAND ##################################################################################################### #
smac_hb_eta_1:
  optimizer: smac_hb
  eta: 1
  num_iterations: 10000000

# learna | metalearna
smac_hb_eta_2_learna:
  optimizer: smac_hb
  eta: 2
  num_iterations: 3

smac_hb_eta_2:
  optimizer: smac_hb
  eta: 2
  num_iterations: 10000000

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
smac_hb_eta_3:
  optimizer: smac_hb
  eta: 3
  num_iterations: 10000000

# SMAC SUCCESSIVE HALVING ############################################################################################ #
smac_sh_eta_1:
  optimizer: smac_hb
  eta: 1
  num_iterations: 10000000

# learna | metalearna
smac_sh_eta_2_learna:
  optimizer: smac_sh
  eta: 2
  num_iterations: 3

smac_sh_eta_2:
  optimizer: smac_sh
  eta: 2
  num_iterations: 10000000

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
smac_sh_eta_3:
  optimizer: smac_sh
  eta: 3
  num_iterations: 10000000

# HPBANDSTER BOHB #################################################################################################### #
# learna | metalearna
hpbandster_bohb_eta_2_learna:
  optimizer: hpbandster_bohb
  eta: 2
  num_iterations: 3

hpbandster_bohb_eta_2:
  optimizer: hpbandster_bohb
  eta: 2
  num_iterations: 10000000

hpbandster_bohb_eta_3_test:
  optimizer: hpbandster_bohb
  eta: 3
  num_iterations: 1

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
hpbandster_bohb_eta_3:
  optimizer: hpbandster_bohb
  eta: 3
  num_iterations: 10000000

# HPBANDSTER RANDOMSEARCH ############################################################################################ #
# learna | metalearna
hpbandster_rs_eta_2_learna:
  optimizer: hpbandster_rs
  eta: 2
  num_iterations: 3

hpbandster_rs_eta_2:
  optimizer: hpbandster_rs
  eta: 2
  num_iterations: 10000000

hpbandster_rs_eta_3_test:
  optimizer: hpbandster_rs
  eta: 3
  num_iterations: 1

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
hpbandster_rs_eta_3:
  optimizer: hpbandster_rs
  eta: 3
  num_iterations: 10000000

# HPBANDSTER HYPERBAND ############################################################################################### #
# learna | metalearna
hpbandster_hb_eta_2_learna:
  optimizer: hpbandster_hb
  eta: 2
  num_iterations: 3

hpbandster_hb_eta_2:
  optimizer: hpbandster_hb
  eta: 2
  num_iterations: 10000000

hpbandster_hb_eta_3_test:
  optimizer: hpbandster_hb
  eta: 3
  num_iterations: 1

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
hpbandster_hb_eta_3:
  optimizer: hpbandster_hb
  eta: 3
  num_iterations: 10000000

# HPBANDSTER H2BO #################################################################################################### #
# learna | metalearna
hpbandster_h2bo_eta_2_learna:
  optimizer: hpbandster_h2bo
  eta: 2
  num_iterations: 3

hpbandster_h2bo_eta_2:
  optimizer: hpbandster_h2bo
  eta: 2
  num_iterations: 10000000

hpbandster_h2bo_eta_3_test:
  optimizer: hpbandster_h2bo
  eta: 3
  num_iterations: 1

# xgboost | cartpolereduced| cartpolefull | NASCifar10ABenchmark | NASCifar10BBenchmark | NASCifar10CBenchmark
# SliceLocalizationBenchmark | ProteinStructureBenchmark | NavalPropulsionBenchmark | ParkinsonsTelemonitoringBenchmark
hpbandster_h2bo_eta_3:
  optimizer: hpbandster_h2bo
  eta: 3
  num_iterations: 10000000
...
