---
# PURE RANDOMSEARCH################################################################################################### #
randomsearch:
  optimizer: randomsearch
  display_name: "random search"

# Autogluon HNAS ############################################################################################################ #
autogluon:
  optimizer: autogluon
  reduction_factor: 3
  scheduler: "hyperband_promotion"
  searcher: "bayesopt"
  display_name: "autogluon"

# DEHB ############################################################################################################### #
dehb:
  optimizer: dehb
  # Options for strategy:
  # ['rand1_bin', 'rand2_bin', 'rand2dir_bin', 'best1_bin', 'best2_bin', 'currenttobest1_bin', 'randtobest1_bin',
  # 'rand1_exp', 'rand2_exp', 'rand2dir_exp', 'best1_exp', 'best2_exp', 'currenttobest1_exp', 'randtobest1_exp']
  strategy: rand1_bin
  mutation_factor: 0.5
  crossover_prob: 0.5
  gens: 1
  eta: 3
  # Options for async_strategy: ['deferred', 'immediate', 'random', 'worst']
  async_strategy: immediate
  display_name: "DEHB"

de:
  # From https://github.com/automl/DEHB/blob/tpami/dehb/examples/svm/run_de_svm.py
  optimizer: de
  pop_size: 20
  mutation_factor: 0.5
  crossover_prob: 0.5
  strategy: rand1_bin
  display_name: "DE"

# DRAGONFLY DEFAULT ################################################################################################## #
dragonfly_default:
  optimizer: dragonfly
  init_iter_per_dim: 10
  init_capital_frac: 0.1 # Ignored since 'init_iter_per_dim' is present
  display_name: "Dragonfly"

# DRAGONFLY REALTIME ################################################################################################# #
dragonfly_realtime:
  optimizer: dragonfly
  init_capital_frac: 0.1

# MUMBO ############################################################################################################## #
mumbo:
  optimizer: mumbo
  init_samples_per_dim: 10
  num_fidelity_values: 5 # Continuous fidelity parameters are discretized according to this; Same value as max_stages
  initial_design: Latin # Two options: [Random, Latin]
  # GP Settings
  n_optimization_restarts: 5
  update_interval: 1
  batch_size: 1
  kernel: matern52  # Can be one of ['rbf', 'matern52']
  # MUMBO acquisition settings
  num_mc_samples: 10
  grid_size: 10000

# FABOLAS MTBO ####################################################################################################### #
fabolas_mtbo:
  optimizer: fabolas
  acquisition: mtbo
  init_samples_per_dim: 10
  num_fidelity_values: 10 # Continuous fidelity parameters are discretized according to this
  marginalize_hypers: false
  initial_design: Latin # Two options: [Random, Latin]
  update_interval: 1
  # MTBO acquisition specific settings
  num_eval_points: 2000

# FABOLAS MUMBO ###################################################################################################### #
fabolas_mumbo:
  optimizer: fabolas
  acquisition: mumbo
  init_samples_per_dim: 10
  num_fidelity_values: 10 # Continuous fidelity parameters are discretized according to this
  marginalize_hypers: false
  initial_design: Latin # Two options: [Random, Latin]
  update_interval: 1
  # MUMBO acquisition specific settings
  num_mc_samples: 10
  grid_size: 10000

# SMAC ##################################################################################################### #
smac_sf:
  optimizer: smac_sf
  display_name: "SMAC SF"

smac_bo:
  optimizer: smac_bo
  display_name: "SMAC BO"

smac_hb_eta_3:
  optimizer: smac_hb
  eta: 3
  max_stages: 5
  display_name: "SMAC-HB"

smac_sh_eta_3:
  optimizer: smac_sh
  eta: 3
  max_stages: 5
  display_name: "SMAC-SH"

smac_hb_eta_2:
  optimizer: smac_hb
  eta: 2
  max_stages: 5
  display_name: "SMAC-HB (eta2)"

smac_sh_eta_2:
  optimizer: smac_sh
  eta: 2
  max_stages: 5
  display_name: "SMAC-SH (eta2)"

# HPBANDSTER BOHB #################################################################################################### #

hpbandster_tpe:
  optimizer: hpbandster_tpe
  display_name: "BOHB TPE"

hpbandster_bohb_eta_3:
  optimizer: hpbandster_bohb
  eta: 3
  max_stages: 5
  display_name: "BOHB"

hpbandster_bohb_eta_2:
  optimizer: hpbandster_bohb
  eta: 2
  max_stages: 5
  display_name: "BOHB (eta2)"

hpbandster_hb_eta_3:
  optimizer: hpbandster_hb
  eta: 3
  max_stages: 5
  display_name: "HB"

hpbandster_hb_eta_2:
  optimizer: hpbandster_hb
  eta: 2
  max_stages: 5
  display_name: "HB (eta2)"
...
