name: Test Optimizer

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: 3.7
            DISPLAY_NAME: "Optimizer autogluon - Py 3.7 - Singularity 3.6"
            SINGULARITY_VERSION: "3.6"
            OPTIMIZER: "autogluon"
          - python-version: 3.7
            DISPLAY_NAME: "Optimizer dehb - Py 3.7 - Singularity 3.6"
            SINGULARITY_VERSION: "3.6"
            OPTIMIZER: "dehb"
          - python-version: 3.7
            DISPLAY_NAME: "Optimizer dragonfly_default - Py 3.7 - Singularity 3.6"
            SINGULARITY_VERSION: "3.6"
            OPTIMIZER: "dragonfly_default"
          - python-version: 3.7
            DISPLAY_NAME: "Optimizer hpbandster_bohb_eta_3 - Py 3.7 - Singularity 3.6"
            SINGULARITY_VERSION: "3.6"
            OPTIMIZER: "hpbandster_bohb_eta_3"
          - python-version: 3.7
            DISPLAY_NAME: "Optimizer ray_hyperopt_asha - Py 3.7 - Singularity 3.6"
            SINGULARITY_VERSION: "3.6"
            OPTIMIZER: "ray_hyperopt_asha"
          - python-version: 3.7
            DISPLAY_NAME: "Optimizer ray_bayesopt_asha - Py 3.7 - Singularity 3.6"
            SINGULARITY_VERSION: "3.6"
            OPTIMIZER: "ray_bayesopt_asha"
          - python-version: 3.7
            DISPLAY_NAME: "Optimizer optuna_tpe_hb - Py 3.7 - Singularity 3.6"
            SINGULARITY_VERSION: "3.6"
            OPTIMIZER: "optuna_tpe_hb"
          - python-version: 3.7
            DISPLAY_NAME: "Optimizer smac_hb_eta_3 - Py 3.7 - Singularity 3.6"
            SINGULARITY_VERSION: "3.6"
            OPTIMIZER: "smac_hb_eta_3"
      fail-fast: false

    name: Tests ${{ matrix.python-version }} ${{ matrix.DISPLAY_NAME }}

    env:
      SINGULARITY_VERSION: ${{ matrix.SINGULARITY_VERSION }}
      OPTIMIZER: ${{ matrix.OPTIMIZER }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Go for Singularity
      if: matrix.USE_SINGULARITY == true
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.15' # The Go version to download (if necessary) and use.
    - name: Install Singularity
      run: chmod +x ./ci_scripts/install_singularity.sh && source ./ci_scripts/install_singularity.sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        chmod +x ./ci_scripts/install_dependencies.sh && source ./ci_scripts/install_dependencies.sh
    - name: Run Tests
      run: |
        echo $PYTHONPATH
        chmod +x ./ci_scripts/run_optimizer.sh && source ./ci_scripts/run_optimizer.sh
